// Copyright (c) 2026 Code Cowboys LLC. All rights reserved.
//
// Generates docs/owner-verification-checklist.md from every
// TODO(owner-verify) marker in the repo (spec §7 Phase 0: the checklist is
// produced by a build step, never maintained by hand).
//
//   dart tool/owner_verify_checklist.dart --write   regenerate the doc
//   dart tool/owner_verify_checklist.dart --check   fail if the doc is stale

import 'dart:io';

const outputPath = 'docs/owner-verification-checklist.md';
const marker = 'TODO(owner-verify)';

const skipDirs = ['.git', '.dart_tool', 'build', '.idea', '.vscode'];
const textExtensions = ['.dart', '.md', '.json', '.yaml', '.yml', '.txt'];

void main(List<String> args) {
  final mode = args.isEmpty ? '--check' : args.first;

  final findings = <({String path, int line, String text})>[];
  for (final entity in Directory('.').listSync(recursive: true)) {
    if (entity is! File) continue;
    final path = entity.path.replaceFirst('./', '');
    if (skipDirs.any((d) => path == d || path.startsWith('$d/'))) continue;
    if (path == outputPath) continue;
    if (!textExtensions.any(path.endsWith)) continue;

    final lines = entity.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      if (lines[i].toLowerCase().contains(marker.toLowerCase())) {
        findings.add((path: path, line: i + 1, text: lines[i].trim()));
      }
    }
  }
  findings.sort((a, b) {
    final byPath = a.path.compareTo(b.path);
    return byPath != 0 ? byPath : a.line.compareTo(b.line);
  });

  final buffer = StringBuffer()
    ..writeln('# Owner sign-off checklist')
    ..writeln()
    ..writeln(
      '<!-- GENERATED by tool/owner_verify_checklist.dart — do not '
      'edit by hand. Run: dart tool/owner_verify_checklist.dart --write -->',
    )
    ..writeln()
    ..writeln(
      'Every `TODO(owner-verify)` marker in the codebase, enumerated '
      'automatically (spec §7 Phase 0). Each item needs the owner\'s '
      'attention against his licensed copy of the standard before the '
      'related rule or value may leave `unverified` status.',
    )
    ..writeln()
    ..writeln('${findings.length} open item(s).')
    ..writeln();
  for (final f in findings) {
    buffer.writeln('- [ ] `${f.path}:${f.line}` — ${f.text}');
  }

  final content = buffer.toString();
  final outFile = File(outputPath);

  if (mode == '--write') {
    outFile.writeAsStringSync(content);
    stdout.writeln(
      'owner-verify-checklist: wrote $outputPath '
      '(${findings.length} items)',
    );
  } else {
    final current = outFile.existsSync() ? outFile.readAsStringSync() : '';
    if (current != content) {
      stderr.writeln(
        'owner-verify-checklist: FAIL — $outputPath is stale. '
        'Run: dart tool/owner_verify_checklist.dart --write',
      );
      exit(1);
    }
    stdout.writeln('owner-verify-checklist: OK (${findings.length} items)');
  }
}
